### PR TITLE
Added bower support

### PR DESCRIPTION
**Pull request by simeg**
Created a `bower.json` file. I hope that the information I provided in the file is correct. I also marked the current code as being `v1.0`. Bower needs information about versions. I also added a simple `.gitignore`.

The package is available with `bower install ng-color-picker`. **After** this merge it will automatically be included where it needs to in projects using e.g. Yeoman, but not as it is right now.

### CODE REVIEW

**Comment by joujiahe** [comment]
Hi @simeg,

Sorry for that I missed your PR.

Bower support is a great idea. Many thanks for your contribution.

**Comment by simeg** [comment]
Hi,

Thanks.

Also, this might sound weird, but I’ve been working on the repo for a few days and really extended the functionality of it. 

Would you mind if I posted it as my own project with a text in the description saying ”Based on ng-color-picker” and a link to your repository of course. 

Kind regards,
Simon

**Comment by simeg** [comment]
Or maybe I should just ask - what license does the repo have?

Regards,
Simon

**Comment by joujiahe** [comment]
Hi @simeg,

Really sorry about missed your PR because the Github mails got filtered in my mailbox.

I have marked this repo under MIT license, just be feel free to use it. Certainly, contributions are always welcome. :)

**Comment by simeg** [comment]
Thank you, Mr Chou :)

Kind regards,
Simon

**Pull request merged**
